language: node_js

node_js:
  - iojs

#services:
  #- mongodb

env:
  - NODE_PATH=./src/

script:
    - ./node_modules/.bin/jscs src/
    - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec test/unit/**/*.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    #- ./node_modules/.bin/mocha tests/integration/*.js
